import React, { useState, useEffect, useMemo } from 'react';
import { triggerRefresh } from '../hooks/useLiveQuery';

import {
  Card, Row, Col, List, Tag, Space, Button, Form, Input, Select,
  DatePicker, TimePicker, Radio, Modal, Timeline, Empty, message,
  Avatar, Checkbox, InputNumber, Tooltip, Divider, Statistic,
  Badge, Popover, App, Dropdown, Tabs
} from 'antd';
import {
  FileTextOutlined, PlusOutlined, CheckCircleOutlined,
  ExclamationCircleOutlined, ClockCircleOutlined, DeleteOutlined,
  EditOutlined, SendOutlined, UserOutlined, WarningOutlined,
  StarOutlined, SaveOutlined, PrinterOutlined, HistoryOutlined,
  BellOutlined, EyeOutlined
} from '@ant-design/icons';
import dayjs from 'dayjs';
import { useLiveQuery } from '../hooks/useLiveQuery';
import { db } from '../db';
import { Baby, HandoverItem, HandoverItemStatus, ShiftType, ShiftRecord, Reminder } from '../types';
import { useAppStore } from '../store/appStore';
import { formatDateTime, formatDuration, getBabyFeedingStats } from '../utils';

const { Option } = Select;
const { TextArea } = Input;
const { RangePicker } = TimePicker;

const SHIFT_OPTIONS: { value: ShiftType; label: string; time: string; icon: string; color: string }[] = [
  { value: 'morning', label: '白班 (早)', time: '08:00 - 16:00', icon: '☀️', color: '#faad14' },
  { value: 'afternoon', label: '中班 (午)', time: '16:00 - 24:00', icon: '🌆', color: '#722ed1' },
  { value: 'night', label: '夜班 (晚)', time: '00:00 - 08:00', icon: '🌙', color: '#1677ff' }
];

const STATUS_CONFIG: Record<HandoverItemStatus, { color: string; label: string; icon: string }> = {
  pending: { color: '#faad14', label: '待处理', icon: '⏳' },
  in_progress: { color: '#1677ff', label: '进行中', icon: '🔄' },
  completed: { color: '#52c41a', label: '已完成', icon: '✅' },
  attention: { color: '#ff4d4f', label: '重点关注', icon: '⚠️' }
};

const ShiftRecordPage: React.FC = () => {
  const {
    currentNurse, setCurrentNurse, pendingHandoverItems,
    addHandoverItem, removeHandoverItem, updateHandoverItem,
    clearHandoverItems, addNotification, setSelectedBaby, setActiveWindow,
    setReminderJump
  } = useAppStore();
  const { modal } = App.useApp();

  const [form] = Form.useForm();
  const [itemForm] = Form.useForm();
  const [itemModalOpen, setItemModalOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<HandoverItem | null>(null);
  const [selectedShiftType, setSelectedShiftType] = useState<ShiftType>(
    (() => {
      const h = dayjs().hour();
      if (h >= 8 && h < 16) return 'morning';
      if (h >= 16) return 'afternoon';
      return 'night';
    })()
  );
  const [oncomingNurse, setOncomingNurse] = useState('');
  const [notes, setNotes] = useState('');
  const [saving, setSaving] = useState(false);
  const [activeTab, setActiveTab] = useState<'new' | 'history'>('new');
  const [historyTab, setHistoryTab] = useState<'history' | 'followup'>('history');
  const [followupFilter, setFollowupFilter] = useState({
    babyId: 'all' as 'all' | number,
    room: 'all' as string,
    status: 'all' as 'all' | HandoverItemStatus
  });
  const [detailModal, setDetailModal] = useState<{
    open: boolean; item?: HandoverItem; shiftId?: number; baby?: Baby;
  }>({ open: false });
  const [autoGeneratedForBabyIds, setAutoGeneratedForBabyIds] = useState<Set<number>>(new Set());

  const babies = useLiveQuery(
    () => db.babies.where('status').equals('active').sortBy('roomNumber'),
    [], []
  ) as Baby[];

  const historyShifts = useLiveQuery(
    async () => {
      const arr = await db.shiftRecords.toArray();
      arr.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
      return arr.slice(0, 50);
    },
    [], []
  ) as ShiftRecord[];

  const allReminders = useLiveQuery(
    () => db.reminders.orderBy('createdAt').reverse().limit(200).toArray(),
    [], []
  ) as Reminder[];

  useEffect(() => {
    form.setFieldsValue({
      shiftType: selectedShiftType,
      shiftDate: dayjs(),
      outgoingNurse: currentNurse,
      startTime: dayjs()
    });
  }, []);

  useEffect(() => {
    if (babies.length > 0) {
      autoGenerateHandoverItems();
    }
  }, [babies]);

  const autoGenerateHandoverItems = async () => {
    const existingAutoIds = new Set(
      pendingHandoverItems
        .filter(i => i.id.startsWith('auto_'))
        .map(i => i.id)
    );

    for (const b of babies) {
      if (!b.id) continue;

      if (autoGeneratedForBabyIds.has(b.id)) continue;

      if (b.allergies && !existingAutoIds.has(`auto_allergy_${b.id}`)) {
        addHandoverItem({
          id: `auto_allergy_${b.id}`,
          babyId: b.id!,
          description: `⚠️ 过敏史: ${b.allergies}`,
          status: 'attention',
          priority: 'high'
        });
      }

      if (b.notes && !existingAutoIds.has(`auto_note_${b.id}`)) {
        addHandoverItem({
          id: `auto_note_${b.id}`,
          babyId: b.id!,
          description: `📋 ${b.notes}`,
          status: 'pending',
          priority: 'medium'
        });
      }

      const stats = await getBabyFeedingStats(b.id!, new Date().toISOString().split('T')[0]);
      if (stats.minutesSinceLast && stats.avgInterval && stats.minutesSinceLast > stats.avgInterval + 30) {
        const feedId = `auto_feed_${b.id}`;
        if (!existingAutoIds.has(feedId)) {
          addHandoverItem({
            id: feedId,
            babyId: b.id!,
            description: `🍼 喂养已超期 ${formatDuration(stats.minutesSinceLast - stats.avgInterval)}，上次${dayjs(stats.lastFeeding?.startTime).format('HH:mm')}`,
            status: 'attention',
            priority: 'high'
          });
        }
      }

      const pendingReminders = await db.reminders
        .filter(r => r.babyId === b.id && r.status === 'pending')
        .toArray();

      for (const r of pendingReminders) {
        const remId = `auto_reminder_${r.id}`;
        if (!existingAutoIds.has(remId)) {
          addHandoverItem({
            id: remId,
            babyId: b.id!,
            description: `🔔 ${r.title} - ${dayjs(r.scheduledTime).format('HH:mm')}${r.assignedTo ? ` (@${r.assignedTo})` : ''}`,
            status: 'pending',
            priority: r.type === 'medication' ? 'high' : 'medium'
          });
        }
      }

      setAutoGeneratedForBabyIds(prev => new Set([...prev, b.id]));
    }
  };

  const groupedItems = useMemo(() => {
    const groups: Record<string, HandoverItem[]> = {};
    for (const item of pendingHandoverItems) {
      const b = babies.find(x => x.id === item.babyId);
      const key = b ? `${b.roomNumber}室 ${b.name}` : '未分配';
      if (!groups[key]) groups[key] = [];
      groups[key].push(item);
    }
    return groups;
  }, [pendingHandoverItems, babies]);

  const highPriorityCount = pendingHandoverItems.filter(i => i.priority === 'high').length;
  const attentionCount = pendingHandoverItems.filter(i => i.status === 'attention').length;
  const completedCount = pendingHandoverItems.filter(i => i.status === 'completed').length;

  const openItemModal = (item?: HandoverItem) => {
    setEditingItem(item || null);
    itemForm.resetFields();
    if (item) {
      itemForm.setFieldsValue({
        babyId: item.babyId,
        description: item.description,
        status: item.status,
        priority: item.priority
      });
    } else {
      itemForm.setFieldsValue({
        status: 'pending',
        priority: 'medium'
      });
    }
    setItemModalOpen(true);
  };

  const handleSaveItem = async () => {
    try {
      const values = await itemForm.validateFields();
      if (editingItem) {
        updateHandoverItem(editingItem.id, { ...values });
        message.success('事项已更新');
      } else {
        addHandoverItem({
          id: `item_${Date.now()}`,
          ...values
        });
        message.success('事项已添加');
      }
      setItemModalOpen(false);
    } catch (err: any) {
      if (!err?.errorFields) message.error('保存失败');
    }
  };

  const handleSubmit = async () => {
    if (pendingHandoverItems.length === 0) {
      message.warning('交班清单为空，请先添加事项');
      return;
    }
    if (!oncomingNurse.trim()) {
      message.warning('请输入接班护士姓名');
      return;
    }

    try {
      setSaving(true);

      const now = new Date().toISOString();
      const shiftInfo = SHIFT_OPTIONS.find(s => s.value === selectedShiftType)!;

      const savedId = await db.shiftRecords.add({
        shiftType: selectedShiftType,
        shiftDate: dayjs().format('YYYY-MM-DD'),
        startTime: now,
        endTime: now,
        oncomingNurse: oncomingNurse.trim(),
        outgoingNurse: currentNurse,
        handoverItems: pendingHandoverItems,
        notes: notes.trim(),
        completed: true,
        createdAt: now
      } as Omit<ShiftRecord, 'id'>);

      for (const item of pendingHandoverItems) {
        if (item.status === 'pending') {
          const b = babies.find(x => x.id === item.babyId);
          const title = item.description.slice(0, 30);
          await db.reminders.add({
            babyId: item.babyId,
            type: 'custom',
            title: `[交班] ${title}`,
            scheduledTime: dayjs().add(1, 'hour').toISOString(),
            status: 'pending',
            repeat: 'none',
            assignedTo: oncomingNurse.trim(),
            notes: item.description,
            handoverId: Number(savedId),
            handoverItemId: item.id,
            createdAt: now
          } as any);
        }
      }

      triggerRefresh();

      addNotification('交班记录已保存，已同步生成提醒给接班护士', 'success');

      modal.success({
        title: '✅ 交班完成！',
        content: (
          <div>
            <div style={{ marginBottom: 12 }}>
              <strong>交班人:</strong> {currentNurse}
            </div>
            <div style={{ marginBottom: 12 }}>
              <strong>接班人:</strong> {oncomingNurse}
            </div>
            <div style={{ marginBottom: 12 }}>
              <strong>交班事项:</strong> 共 {pendingHandoverItems.length} 项
            </div>
            <div style={{ color: '#666' }}>
              已将未完成事项转为接班护士的待办提醒，可在「历史跟进」视图追踪
            </div>
          </div>
        ),
        okText: '确定',
        onOk: () => {
          clearHandoverItems();
          setAutoGeneratedForBabyIds(new Set());
          setCurrentNurse(oncomingNurse.trim());
          setOncomingNurse('');
          setNotes('');
          setActiveTab('history');
          setHistoryTab('followup');
          triggerRefresh();
        }
      });

    } catch (err) {
      message.error('交班记录保存失败');
    } finally {
      setSaving(false);
    }
  };

  const renderNewShift = () => (
    <Row gutter={20} style={{ height: '100%', padding: 20 }}>
      <Col xs={24} md={14} style={{ display: 'flex', flexDirection: 'column' }}>
        <Card
          title={
            <Space>
              <FileTextOutlined style={{ color: '#ff85a2' }} />
              <span>📝 交班事项清单</span>
              {highPriorityCount > 0 && (
                <Badge count={highPriorityCount} style={{ background: '#ff4d4f' }} offset={[4, 0]}>
                  <Tag color="red" style={{ margin: 0 }}>高优先级</Tag>
                </Badge>
              )}
            </Space>
          }
          extra={
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => openItemModal()}
              style={{ background: 'linear-gradient(135deg, #ff85a2, #ff5c7a)', border: 'none' }}
            >
              手动添加事项
            </Button>
          }
          style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}
          bodyStyle={{ flex: 1, overflow: 'auto', padding: 16 }}
        >
          {pendingHandoverItems.length === 0 ? (
            <Empty
              description="暂无交班事项"
              style={{ padding: 40 }}
            >
              <Space>
                <Button onClick={autoGenerateHandoverItems} icon={<HistoryOutlined />}>
                  自动生成建议事项
                </Button>
                <Button type="primary" onClick={() => openItemModal()} icon={<PlusOutlined />}>
                  手动添加
                </Button>
              </Space>
            </Empty>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {Object.entries(groupedItems).map(([groupKey, items]) => {
                const b = babies.find(x => x.id === items[0]?.babyId);
                return (
                  <div key={groupKey}>
                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 8,
                      marginBottom: 8,
                      paddingLeft: 8,
                      borderLeft: '3px solid #ff85a2',
                      fontWeight: 600,
                      fontSize: 14
                    }}>
                      {b && (
                        <Avatar
                          size={28}
                          style={{
                            background: b.gender === 'male'
                              ? 'linear-gradient(135deg, #69b1ff, #1677ff)'
                              : 'linear-gradient(135deg, #ffb7d5, #ff5c7a)',
                            fontSize: 12
                          }}
                          onClick={() => { setSelectedBaby(b); setActiveWindow('babyTimeline'); }}
                        >
                          {b.name.charAt(0)}
                        </Avatar>
                      )}
                      <span>{groupKey}</span>
                      <Tag color="default" style={{ marginLeft: 4 }}>
                        {items.length} 项
                      </Tag>
                    </div>
                    <List
                      size="small"
                      bordered
                      dataSource={items}
                      style={{ borderRadius: 8, overflow: 'hidden' }}
                      renderItem={item => (
                        <List.Item
                          style={{
                            padding: '12px 16px',
                            background: item.status === 'attention' ? '#fff7f6' : undefined,
                            borderLeft: `4px solid ${STATUS_CONFIG[item.status].color}`
                          }}
                          actions={[
                            <Button
                              type="text"
                              size="small"
                              icon={<EditOutlined />}
                              onClick={() => openItemModal(item)}
                            >编辑</Button>,
                            <Checkbox
                              checked={item.status === 'completed'}
                              onChange={e => updateHandoverItem(item.id, {
                                status: e.target.checked ? 'completed' : 'pending'
                              })}
                            >完成</Checkbox>,
                            <Button
                              type="text"
                              size="small"
                              danger
                              icon={<DeleteOutlined />}
                              onClick={() => removeHandoverItem(item.id)}
                            />
                          ]}
                        >
                          <List.Item.Meta
                            avatar={
                              <span style={{
                                display: 'inline-flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                width: 36, height: 36,
                                borderRadius: '50%',
                                background: `${STATUS_CONFIG[item.status].color}22`,
                                fontSize: 16
                              }}>
                                {STATUS_CONFIG[item.status].icon}
                              </span>
                            }
                            title={
                              <Space>
                                <span
                                  style={{
                                    cursor: 'pointer',
                                    textDecoration: item.status === 'completed' ? 'line-through' : 'none',
                                    opacity: item.status === 'completed' ? 0.6 : 1
                                  }}
                                  onClick={() => {
                                    const b = babies.find(x => x.id === item.babyId);
                                    if (b) { setSelectedBaby(b); setActiveWindow('babyTimeline'); }
                                  }}
                                >
                                  {item.description}
                                </span>
                                <Tag
                                  color={item.priority === 'high' ? 'red' : item.priority === 'medium' ? 'orange' : 'default'}
                                  style={{ margin: 0 }}
                                >
                                  {item.priority === 'high' ? '❗高' : item.priority === 'medium' ? '中' : '低'}
                                </Tag>
                                <Dropdown
                                  trigger={['click']}
                                  menu={{
                                    items: (Object.keys(STATUS_CONFIG) as HandoverItemStatus[]).map(k => ({
                                      key: k,
                                      icon: <span>{STATUS_CONFIG[k].icon}</span>,
                                      label: STATUS_CONFIG[k].label,
                                      onClick: () => updateHandoverItem(item.id, { status: k })
                                    }))
                                  }}
                                >
                                  <Tag color={STATUS_CONFIG[item.status].color} style={{ cursor: 'pointer', margin: 0 }}>
                                    {STATUS_CONFIG[item.status].label} ▼
                                  </Tag>
                                </Dropdown>
                              </Space>
                            }
                          />
                        </List.Item>
                      )}
                    />
                  </div>
                );
              })}
            </div>
          )}
        </Card>
      </Col>

      <Col xs={24} md={10} style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        <Card title={
          <Space>
            <ClockCircleOutlined style={{ color: '#1677ff' }} />
            班次信息
          </Space>
        }>
          <Form form={form} layout="vertical">
            <Form.Item name="shiftType" label="选择班次" rules={[{ required: true }]}>
              <Radio.Group
                value={selectedShiftType}
                onChange={e => setSelectedShiftType(e.target.value)}
                style={{ width: '100%' }}
              >
                {SHIFT_OPTIONS.map(opt => (
                  <Radio.Button
                    key={opt.value}
                    value={opt.value}
                    style={{
                      width: '33.33%',
                      textAlign: 'center',
                      height: 'auto',
                      padding: '12px 8px',
                      borderColor: selectedShiftType === opt.value ? opt.color : undefined,
                      background: selectedShiftType === opt.value ? `${opt.color}11` : undefined
                    }}
                  >
                    <div style={{ fontSize: 20 }}>{opt.icon}</div>
                    <div style={{ fontSize: 12, fontWeight: 600, color: opt.color }}>{opt.label}</div>
                    <div style={{ fontSize: 10, color: '#999' }}>{opt.time}</div>
                  </Radio.Button>
                ))}
              </Radio.Group>
            </Form.Item>
            <Row gutter={12}>
              <Col span={12}>
                <Form.Item label="交班日期">
                  <div style={{
                    padding: '8px 12px',
                    background: '#f5f5f5',
                    borderRadius: 6,
                    fontSize: 14,
                    fontWeight: 500
                  }}>
                    📅 {dayjs().format('YYYY-MM-DD')}
                  </div>
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="交班时间">
                  <div style={{
                    padding: '8px 12px',
                    background: '#f5f5f5',
                    borderRadius: 6,
                    fontSize: 14,
                    fontWeight: 500
                  }}>
                    🕒 {dayjs().format('HH:mm')}
                  </div>
                </Form.Item>
              </Col>
            </Row>
            <Row gutter={12}>
              <Col span={12}>
                <Form.Item label="交班护士 (您)">
                  <div style={{
                    padding: '8px 12px',
                    background: 'linear-gradient(135deg, #e6f4ff, #f0f5ff)',
                    borderRadius: 6,
                    fontSize: 14,
                    fontWeight: 600,
                    color: '#1677ff',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 6
                  }}>
                    👩‍⚕️ {currentNurse}
                  </div>
                </Form.Item>
              </Col>
              <Col span={12}>
                <Form.Item label="接班护士" required>
                  <Input
                    prefix={<UserOutlined />}
                    value={oncomingNurse}
                    onChange={e => setOncomingNurse(e.target.value)}
                    placeholder="请输入姓名"
                  />
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>

        <Card
          title={
            <Space>
              <StarOutlined style={{ color: '#faad14' }} />
              统计概览
            </Space>
          }
          size="small"
        >
          <Row gutter={[8, 8]}>
            <Col span={12}>
              <div style={{
                padding: 12,
                borderRadius: 8,
                background: pendingHandoverItems.length > 0 ? '#fffbe6' : '#f5f5f5',
                textAlign: 'center'
              }}>
                <div style={{ fontSize: 24, fontWeight: 700, color: '#faad14' }}>
                  {pendingHandoverItems.length}
                </div>
                <div style={{ fontSize: 12, color: '#666' }}>事项总数</div>
              </div>
            </Col>
            <Col span={12}>
              <div style={{
                padding: 12,
                borderRadius: 8,
                background: attentionCount > 0 ? '#fff2f0' : '#f5f5f5',
                textAlign: 'center'
              }}>
                <div style={{
                  fontSize: 24,
                  fontWeight: 700,
                  color: attentionCount > 0 ? '#ff4d4f' : '#999'
                }}>
                  {attentionCount}
                </div>
                <div style={{ fontSize: 12, color: '#666' }}>需重点关注</div>
              </div>
            </Col>
            <Col span={12}>
              <div style={{
                padding: 12,
                borderRadius: 8,
                background: completedCount > 0 ? '#f6ffed' : '#f5f5f5',
                textAlign: 'center'
              }}>
                <div style={{ fontSize: 24, fontWeight: 700, color: '#52c41a' }}>
                  {completedCount}
                </div>
                <div style={{ fontSize: 12, color: '#666' }}>本班已完成</div>
              </div>
            </Col>
            <Col span={12}>
              <div style={{
                padding: 12,
                borderRadius: 8,
                background: highPriorityCount > 0 ? '#fff2f0' : '#f5f5f5',
                textAlign: 'center'
              }}>
                <div style={{
                  fontSize: 24,
                  fontWeight: 700,
                  color: highPriorityCount > 0 ? '#ff4d4f' : '#999'
                }}>
                  {highPriorityCount}
                </div>
                <div style={{ fontSize: 12, color: '#666' }}>高优先级</div>
              </div>
            </Col>
          </Row>
        </Card>

        <Card title="💬 交班备注" size="small" style={{ flex: 1 }}>
          <TextArea
            rows={5}
            value={notes}
            onChange={e => setNotes(e.target.value)}
            placeholder="请填写本班次特殊情况、重要事件、需特别交代的事项等..."
            style={{ resize: 'none' }}
          />
        </Card>

        <Button
          type="primary"
          size="large"
          icon={<SendOutlined />}
          onClick={handleSubmit}
          loading={saving}
          disabled={pendingHandoverItems.length === 0 || !oncomingNurse.trim()}
          style={{
            background: 'linear-gradient(135deg, #52c41a, #389e0d)',
            border: 'none',
            height: 48,
            fontSize: 15,
            fontWeight: 600,
            boxShadow: '0 4px 12px rgba(82, 196, 26, 0.3)'
          }}
        >
          ✅ 确认完成交班
        </Button>
      </Col>
    </Row>
  );

  const rooms = useMemo(() => {
    const s = new Set<string>();
    babies.forEach(b => s.add(b.roomNumber));
    return Array.from(s);
  }, [babies]);

  const flatHandoverItems = useMemo(() => {
    const items: Array<{
      item: HandoverItem; shiftId: number; shiftRecord: ShiftRecord; baby?: Baby;
      relatedReminder?: Reminder;
    }> = [];
    for (const rec of historyShifts) {
      if (!rec.id) continue;
      for (const it of rec.handoverItems) {
        const baby = babies.find(b => b.id === it.babyId);
        const reminder = allReminders.find(
          r => r.handoverId === Number(rec.id) &&
            (r.handoverItemId === it.id ||
              (r.notes?.includes(it.description.slice(0, 20)) ||
                r.title?.includes(it.description.slice(0, 20))))
        );
        items.push({ item: it, shiftId: Number(rec.id), shiftRecord: rec, baby, relatedReminder: reminder });
      }
    }
    return items;
  }, [historyShifts, babies, allReminders]);

  const filteredFollowupItems = useMemo(() => {
    return flatHandoverItems.filter(f => {
      if (followupFilter.babyId !== 'all' && f.item.babyId !== followupFilter.babyId) return false;
      if (followupFilter.room !== 'all' && f.baby?.roomNumber !== followupFilter.room) return false;
      if (followupFilter.status !== 'all' && f.item.status !== followupFilter.status) return false;
      return true;
    });
  }, [flatHandoverItems, followupFilter]);

  const followupStats = useMemo(() => {
    const total = flatHandoverItems.length;
    const toReminder = flatHandoverItems.filter(f => f.relatedReminder).length;
    const completed = flatHandoverItems.filter(f =>
      f.item.status === 'completed' ||
      f.relatedReminder?.status === 'completed'
    ).length;
    const pending = total - completed;
    return { total, toReminder, completed, pending };
  }, [flatHandoverItems]);

  const renderFollowupView = () => {
    const openDetail = (it: typeof flatHandoverItems[0]) => {
      setDetailModal({
        open: true, item: it.item, shiftId: it.shiftId, baby: it.baby
      });
    };

    const goToReminder = (rem: Reminder, babyId?: number) => {
      setReminderJump(Number(rem.id), babyId || null);
      setActiveWindow('careReminder');
      addNotification('已跳转到护理提醒，已自动定位到对应提醒条', 'success');
    };

    if (flatHandoverItems.length === 0) {
      return <Empty description="暂无交接事项可跟进，请先完成一次交班" style={{ padding: 60 }} />;
    }

    return (
      <div>
        <Card style={{ marginBottom: 16 }} styles={{ body: { padding: '16px 20px' } }}>
          <Row gutter={[12, 12]} align="middle">
            <Col span={5}>
              <Statistic title="交接事项总数" value={followupStats.total} />
            </Col>
            <Col span={5}>
              <Statistic title="已转提醒" value={followupStats.toReminder} prefix={<BellOutlined />} valueStyle={{ color: '#1890ff' }} />
            </Col>
            <Col span={5}>
              <Statistic title="已处理完成" value={followupStats.completed} valueStyle={{ color: '#52c41a' }} />
            </Col>
            <Col span={5}>
              <Statistic title="待跟进处理" value={followupStats.pending} valueStyle={{ color: '#faad14' }} />
            </Col>
          </Row>
        </Card>

        <Card style={{ marginBottom: 16 }} styles={{ body: { padding: 12 } }}>
          <Space wrap size="large">
            <div>
              <span style={{ fontWeight: 600, marginRight: 8 }}>🏠 房间:</span>
              <Select
                style={{ width: 120 }}
                value={followupFilter.room}
                onChange={v => setFollowupFilter(p => ({ ...p, room: v }))}
                options={[
                  { label: '全部房间', value: 'all' },
                  ...rooms.map(r => ({ label: `${r}室`, value: r }))
                ]}
              />
            </div>
            <div>
              <span style={{ fontWeight: 600, marginRight: 8 }}>👶 宝宝:</span>
              <Select
                style={{ width: 150 }}
                value={followupFilter.babyId}
                onChange={v => setFollowupFilter(p => ({ ...p, babyId: v }))}
                options={[
                  { label: '全部宝宝', value: 'all' as any },
                  ...babies.map(b => ({ label: `${b.name}`, value: b.id! as any }))
                ]}
              />
            </div>
            <div>
              <span style={{ fontWeight: 600, marginRight: 8 }}>📌 状态:</span>
              <Select
                style={{ width: 130 }}
                value={followupFilter.status}
                onChange={v => setFollowupFilter(p => ({ ...p, status: v }))}
                options={[
                  { label: '全部状态', value: 'all' as any },
                  { label: '待处理', value: 'pending' as any },
                  { label: '处理中', value: 'in_progress' as any },
                  { label: '重点关注', value: 'attention' as any },
                  { label: '已完成', value: 'completed' as any }
                ]}
              />
            </div>
            <div style={{ marginLeft: 'auto' }}>
              <Tag color="purple">共 {filteredFollowupItems.length} 条事项</Tag>
            </div>
          </Space>
        </Card>

        <List
          dataSource={filteredFollowupItems}
          locale={{ emptyText: '当前筛选条件下无事项' }}
          renderItem={(row) => {
            const cfg = STATUS_CONFIG[row.item.status];
            const reminder = row.relatedReminder;
            const done = row.item.status === 'completed' || reminder?.status === 'completed';

            return (
              <Card
                hoverable
                onClick={() => openDetail(row)}
                style={{ marginBottom: 12, cursor: 'pointer' }}
                styles={{ body: { padding: 16 } }}
              >
                <Row gutter={12} align="middle">
                  <Col span={12}>
                    <Space>
                      {row.baby && (
                        <>
                          <Avatar size="small" style={{ background: row.baby.gender === 'male' ? '#1890ff' : '#ff85a2' }}>
                            {row.baby.name[0]}
                          </Avatar>
                          <Tag color="purple">{row.baby.name}</Tag>
                        </>
                      )}
                      <Tag color={row.baby ? 'blue' : 'default'}>
                        {row.baby ? `${row.baby.roomNumber}室${row.baby.bedNumber}床` : '未分配床位'}
                      </Tag>
                    </Space>
                  </Col>
                  <Col span={6}>
                    <Tag color={cfg.color} icon={<span>{cfg.icon}</span>}>
                      {cfg.label}
                    </Tag>
                    <Tag color={row.item.priority === 'high' ? 'red' : row.item.priority === 'medium' ? 'orange' : 'default'}
                      style={{ marginLeft: 6 }}>
                      {row.item.priority === 'high' ? '高优' : row.item.priority === 'medium' ? '中优' : '低优'}
                    </Tag>
                  </Col>
                  <Col span={4}>
                    {reminder ? (
                      <Tag color={reminder.status === 'completed' ? 'green' :
                        reminder.status === 'pending' ? 'blue' :
                          reminder.status === 'missed' ? 'orange' : 'default'}
                        onClick={(e) => { e.stopPropagation(); goToReminder(reminder); }}
                        style={{ cursor: 'pointer' }}>
                        <BellOutlined /> 已转提醒
                        {reminder.status === 'completed' ? '✅' : '⏳'}
                      </Tag>
                    ) : done ? (
                      <Tag color="green">✅ 交班时已完成</Tag>
                    ) : (
                      <Tag color="default">未转提醒</Tag>
                    )}
                  </Col>
                  <Col span={2} style={{ textAlign: 'right' }}>
                    <span style={{ fontSize: 20 }}>{cfg.icon}</span>
                  </Col>
                </Row>
                <div style={{ marginTop: 10, fontSize: 14, fontWeight: 500 }}>
                  {row.item.description}
                </div>
                <div style={{ marginTop: 8, display: 'flex', justifyContent: 'space-between', color: '#888', fontSize: 12 }}>
                  <span>
                    📅 来源：{row.shiftRecord.shiftDate}
                    {' '}{SHIFT_OPTIONS.find(s => s.value === row.shiftRecord.shiftType)?.label}
                    {' · '}👩‍⚕️ {row.shiftRecord.outgoingNurse} → {row.shiftRecord.oncomingNurse}
                  </span>
                  <span>{formatDateTime(row.shiftRecord.createdAt)} · 点击查看详情</span>
                </div>
              </Card>
            );
          }}
        />
      </div>
    );
  };

  const renderHistory = () => (
    <div style={{ padding: 20 }}>
      <Tabs
        activeKey={historyTab}
        onChange={k => setHistoryTab(k as any)}
        items={[
          {
            key: 'history',
            label: <span><HistoryOutlined /> 交班记录列表</span>,
            children: (
              historyShifts.length === 0 ? (
                <Empty description="暂无交班历史记录" style={{ padding: 60 }} />
              ) : (
                <List
                  dataSource={historyShifts}
                  renderItem={(record) => {
                    const sInfo = SHIFT_OPTIONS.find(s => s.value === record.shiftType)!;
                    return (
                      <Card
                        key={record.id}
                        style={{ marginBottom: 16, borderRadius: 12 }}
                        bodyStyle={{ padding: 0 }}
                      >
                        <div style={{
                          padding: '16px 20px',
                          background: `linear-gradient(135deg, ${sInfo.color}11 0%, #fff 100%)`,
                          borderBottom: '1px solid #f0f0f0',
                          borderRadius: '12px 12px 0 0',
                          display: 'flex',
                          justifyContent: 'space-between',
                          alignItems: 'center'
                        }}>
                          <Space size="large">
                            <div style={{ fontSize: 28 }}>{sInfo.icon}</div>
                            <div>
                              <div style={{ fontSize: 16, fontWeight: 700 }}>
                                {sInfo.label}
                                <Tag color={sInfo.color} style={{ marginLeft: 12 }}>
                                  {record.shiftDate}
                                </Tag>
                              </div>
                              <div style={{ fontSize: 13, color: '#666', marginTop: 4 }}>
                                👩‍⚕️ <strong>{record.outgoingNurse}</strong>
                                {' → '}
                                👩‍⚕️ <strong>{record.oncomingNurse}</strong>
                              </div>
                            </div>
                          </Space>
                          <Space>
                            <Tag color={record.completed ? 'green' : 'orange'}>
                              {record.completed ? '✅ 已完成' : '⏳ 进行中'}
                            </Tag>
                            <div style={{ fontSize: 12, color: '#999' }}>
                              {formatDateTime(record.createdAt)}
                            </div>
                            <Button size="small" icon={<BellOutlined />}
                              onClick={() => setHistoryTab('followup')}>
                              跟进事项
                            </Button>
                          </Space>
                        </div>

                        <div style={{ padding: 16 }}>
                          <Row gutter={[12, 12]}>
                            <Col span={6}>
                              <Statistic title="交班事项" value={record.handoverItems.length} />
                            </Col>
                            <Col span={6}>
                              <Statistic
                                title="已完成"
                                value={record.handoverItems.filter(i => i.status === 'completed').length}
                                valueStyle={{ color: '#52c41a' }}
                              />
                            </Col>
                            <Col span={6}>
                              <Statistic
                                title="重点关注"
                                value={record.handoverItems.filter(i => i.status === 'attention').length}
                                valueStyle={{ color: '#ff4d4f' }}
                              />
                            </Col>
                            <Col span={6}>
                              <Statistic
                                title="待处理"
                                value={record.handoverItems.filter(i => i.status === 'pending' || i.status === 'in_progress').length}
                                valueStyle={{ color: '#faad14' }}
                              />
                            </Col>
                          </Row>

                          <Divider style={{ margin: '12px 0' }} />

                          <Timeline
                            style={{ maxHeight: 260, overflow: 'auto' }}
                            items={record.handoverItems.map(item => {
                              const b = babies.find(x => x.id === item.babyId);
                              return {
                                color: STATUS_CONFIG[item.status].color,
                                dot: <span style={{ fontSize: 14 }}>{STATUS_CONFIG[item.status].icon}</span>,
                                children: (
                                  <div>
                                    <div style={{ fontWeight: 500 }}>
                                      {b && (
                                        <Tag color="purple" style={{ marginRight: 8 }}>
                                          {b.name}
                                        </Tag>
                                      )}
                                      {item.description}
                                    </div>
                                    <div style={{ marginTop: 4 }}>
                                      <Tag
                                        style={{ margin: 0 }}
                                        color={STATUS_CONFIG[item.status].color}
                                      >
                                        {STATUS_CONFIG[item.status].label}
                                      </Tag>
                                      <Tag
                                        style={{ marginLeft: 8 }}
                                        color={item.priority === 'high' ? 'red' : item.priority === 'medium' ? 'orange' : 'default'}
                                      >
                                        {item.priority === 'high' ? '高优先级' : item.priority === 'medium' ? '中优先级' : '低优先级'}
                                      </Tag>
                                    </div>
                                  </div>
                                )
                              };
                            })}
                          />

                          {record.notes && (
                            <>
                              <Divider style={{ margin: '12px 0' }} />
                              <div style={{
                                padding: 12,
                                background: '#fafafa',
                                borderRadius: 8,
                                fontSize: 13,
                                color: '#666'
                              }}>
                                <strong>📝 交班备注:</strong> {record.notes}
                              </div>
                            </>
                          )}
                        </div>
                      </Card>
                    );
                  }}
                />
              )
            )
          },
          {
            key: 'followup',
            label: <span><EyeOutlined /> 事项跟进视图 ({flatHandoverItems.length})</span>,
            children: renderFollowupView()
          }
        ]}
      />
    </div>
  );

  return (
    <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
      <div style={{
        padding: '12px 20px',
        borderBottom: '1px solid #f0f0f0',
        display: 'flex',
        alignItems: 'center',
        gap: 12,
        background: '#fff'
      }}>
        <Radio.Group
          value={activeTab}
          onChange={e => setActiveTab(e.target.value)}
          optionType="button"
          buttonStyle="solid"
        >
          <Radio.Button value="new" style={{ padding: '6px 20px', fontWeight: 600 }}>
            <FileTextOutlined /> 新建交班
          </Radio.Button>
          <Radio.Button value="history" style={{ padding: '6px 20px', fontWeight: 600 }}>
            <HistoryOutlined /> 历史记录 ({historyShifts.length})
          </Radio.Button>
        </Radio.Group>

        <div style={{ flex: 1 }} />

        {activeTab === 'new' && (
          <Space>
            <Button icon={<WarningOutlined />} onClick={autoGenerateHandoverItems}>
              自动生成建议
            </Button>
            <PopconfirmWrapper onConfirm={() => {
              clearHandoverItems();
              message.success('清单已清空');
            }}>
              <Button danger>清空清单</Button>
            </PopconfirmWrapper>
          </Space>
        )}
      </div>

      <div style={{ flex: 1, overflow: 'auto' }}>
        {activeTab === 'new' ? renderNewShift() : renderHistory()}
      </div>

      <Modal
        title={editingItem ? '编辑交班事项' : '添加交班事项'}
        open={itemModalOpen}
        onOk={handleSaveItem}
        onCancel={() => setItemModalOpen(false)}
        okText="保存"
        cancelText="取消"
      >
        <Form form={itemForm} layout="vertical">
          <Form.Item
            name="babyId"
            label="关联宝宝"
            rules={[{ required: true, message: '请选择宝宝' }]}
          >
            <Select placeholder="请选择宝宝" showSearch optionFilterProp="label">
              {babies.map(b => (
                <Option key={b.id} value={b.id} label={`${b.name} ${b.roomNumber}${b.bedNumber}`}>
                  <Space>
                    <Avatar size="small" style={{
                      background: b.gender === 'male'
                        ? 'linear-gradient(135deg, #69b1ff, #1677ff)'
                        : 'linear-gradient(135deg, #ffb7d5, #ff5c7a)',
                      fontSize: 12
                    }}>
                      {b.name.charAt(0)}
                    </Avatar>
                    <span>{b.name}</span>
                    <Tag color="default">{b.roomNumber}{b.bedNumber}</Tag>
                  </Space>
                </Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item
            name="description"
            label="事项描述"
            rules={[{ required: true, message: '请输入事项描述' }]}
          >
            <TextArea rows={3} placeholder="请详细描述需要交接的事项" />
          </Form.Item>
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item name="status" label="状态" rules={[{ required: true }]}>
                <Select>
                  {(Object.keys(STATUS_CONFIG) as HandoverItemStatus[]).map(k => (
                    <Option key={k} value={k}>
                      {STATUS_CONFIG[k].icon} {STATUS_CONFIG[k].label}
                    </Option>
                  ))}
                </Select>
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item name="priority" label="优先级" rules={[{ required: true }]}>
                <Select>
                  <Option value="high">❗ 高优先级</Option>
                  <Option value="medium">中优先级</Option>
                  <Option value="low">低优先级</Option>
                </Select>
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Modal>

      <Modal
        title="📋 交接事项跟进详情"
        open={detailModal.open}
        onCancel={() => setDetailModal({ open: false })}
        footer={[
          detailModal.item && (detailModal.item.status === 'pending' || detailModal.item.status === 'attention') && !detailModal.item?.id?.startsWith('auto_allergy') ? (
            <Button key="remind" icon={<BellOutlined />} onClick={() => {
              if (detailModal.item) {
                const item = detailModal.item;
                const reminder = flatHandoverItems.find(
                  f => f.item.id === item.id && f.relatedReminder
                )?.relatedReminder;
                if (reminder) {
                  setReminderJump(Number(reminder.id), reminder.babyId);
                  setActiveWindow('careReminder');
                  addNotification('已跳转到护理提醒，已自动定位到对应提醒条', 'success');
                } else {
                  Modal.confirm({
                    title: '转为跟进提醒?',
                    content: '将为接班护士生成一条待办提醒',
                    onOk: async () => {
                      await db.reminders.add({
                        babyId: detailModal.item!.babyId,
                        type: 'custom',
                        title: `[交接] ${detailModal.item!.description.slice(0, 30)}`,
                        scheduledTime: dayjs().add(30, 'minute').toISOString(),
                        status: 'pending',
                        repeat: 'none',
                        assignedTo: currentNurse,
                        notes: detailModal.item!.description,
                        handoverId: detailModal.shiftId,
                        handoverItemId: detailModal.item!.id,
                        createdAt: new Date().toISOString()
                      } as any);
                      triggerRefresh();
                      message.success('已生成提醒');
                      setDetailModal({ open: false });
                    }
                  });
                }
              }
            }}>
              {flatHandoverItems.find(f => f.item.id === detailModal.item?.id && f.relatedReminder)
                ? '查看对应提醒'
                : '转为跟进提醒'}
            </Button>
          ) : null,
          <Button key="close" onClick={() => setDetailModal({ open: false })}>关闭</Button>
        ]}
        width={720}
      >
        {detailModal.item && (
          <Space direction="vertical" size="large" style={{ width: '100%' }}>
            <Card style={{ background: '#f0f7ff', borderRadius: 8 }} styles={{ body: { padding: 16 } }}>
              <Row gutter={16}>
                <Col span={12}>
                  <Space>
                    <Avatar size={48} style={{
                      background: detailModal.baby?.gender === 'male'
                        ? 'linear-gradient(135deg, #69b1ff, #1677ff)'
                        : 'linear-gradient(135deg, #ffb7d5, #ff5c7a)'
                    }}>
                      {detailModal.baby?.name.charAt(0)}
                    </Avatar>
                    <div>
                      <div style={{ fontSize: 16, fontWeight: 700 }}>{detailModal.baby?.name || '未分配'}</div>
                      <div style={{ color: '#666', fontSize: 12 }}>
                        {detailModal.baby ? `${detailModal.baby.roomNumber}室${detailModal.baby.bedNumber}床` : ''}
                      </div>
                    </div>
                  </Space>
                </Col>
                <Col span={12} style={{ textAlign: 'right' }}>
                  <Tag color={STATUS_CONFIG[detailModal.item.status].color}
                    style={{ fontSize: 13, padding: '4px 12px' }}>
                    {STATUS_CONFIG[detailModal.item.status].icon} {STATUS_CONFIG[detailModal.item.status].label}
                  </Tag>
                  <Tag color={detailModal.item.priority === 'high' ? 'red' : detailModal.item.priority === 'medium' ? 'orange' : 'default'}
                    style={{ fontSize: 13, padding: '4px 12px' }}>
                    {detailModal.item.priority === 'high' ? '高优' : detailModal.item.priority === 'medium' ? '中优' : '低优'}
                  </Tag>
                </Col>
              </Row>
              <Divider style={{ margin: '12px 0' }} />
              <div style={{ fontSize: 14 }}>
                <strong style={{ color: '#666' }}>事项描述：</strong>
                <span style={{ fontSize: 15, marginLeft: 8 }}>{detailModal.item.description}</span>
              </div>
            </Card>

            {(() => {
              const row = flatHandoverItems.find(f => f.item.id === detailModal.item!.id);
              const reminder = row?.relatedReminder;
              const src = row?.shiftRecord;

              return (
                <Card title="🔗 关联信息" styles={{ body: { padding: 16 } }}>
                  <Row gutter={[16, 12]}>
                    <Col span={12}>
                      <div style={{ color: '#888', fontSize: 12 }}>交班信息</div>
                      <div style={{ fontSize: 13, marginTop: 4 }}>
                        {src ? (
                          <div>
                            <div>📅 {src.shiftDate} {SHIFT_OPTIONS.find(s => s.value === src.shiftType)?.label}</div>
                            <div>👩‍⚕️ {src.outgoingNurse} → 👩‍⚕️ {src.oncomingNurse}</div>
                            <div style={{ color: '#888' }}>{formatDateTime(src.createdAt)}</div>
                          </div>
                        ) : <span style={{ color: '#999' }}>暂无</span>}
                      </div>
                    </Col>
                    <Col span={12}>
                      <div style={{ color: '#888', fontSize: 12 }}>后续提醒</div>
                      <div style={{ fontSize: 13, marginTop: 4 }}>
                        {reminder ? (
                          <div>
                            <Tag color={
                              reminder.status === 'completed' ? 'green' :
                                reminder.status === 'pending' ? 'blue' :
                                  reminder.status === 'missed' ? 'orange' : 'default'
                            } style={{ fontSize: 12 }}>
                              {reminder.status === 'completed' ? '✅ 已完成' :
                                reminder.status === 'pending' ? '⏳ 待处理' :
                                  reminder.status === 'missed' ? '⚠️ 已错过' : '已取消'}
                            </Tag>
                            <div style={{ marginTop: 4 }}>📌 {reminder.title}</div>
                            <div style={{ color: '#888' }}>
                              🕐 {formatDateTime(reminder.scheduledTime)}
                              {reminder.assignedTo ? ` · 👩‍⚕️ ${reminder.assignedTo}` : ''}
                            </div>
                            {reminder.completedAt && (
                              <div style={{ color: '#52c41a' }}>✅ 完成于 {formatDateTime(reminder.completedAt)}</div>
                            )}
                          </div>
                        ) : detailModal.item.status === 'completed' ? (
                          <Tag color="green" style={{ fontSize: 12 }}>✅ 交班时已完成，无需转提醒</Tag>
                        ) : (
                          <Tag color="default" style={{ fontSize: 12 }}>⏳ 尚未生成跟进提醒</Tag>
                        )}
                      </div>
                    </Col>
                  </Row>
                </Card>
              );
            })()}

            {(() => {
              const babyAllergies = detailModal.baby?.allergies;
              const babyNotes = detailModal.baby?.notes;
              if (!babyAllergies && !babyNotes) return null;
              return (
                <Card title="⚠️ 宝宝档案重点" styles={{ body: { padding: 16 } }}>
                  <Space direction="vertical" size="small" style={{ width: '100%' }}>
                    {babyAllergies && <div><strong>过敏史:</strong> <Tag color="red">{babyAllergies}</Tag></div>}
                    {babyNotes && <div><strong>特殊备注:</strong> {babyNotes}</div>}
                  </Space>
                </Card>
              );
            })()}
          </Space>
        )}
      </Modal>
    </div>
  );
};

const PopconfirmWrapper: React.FC<{
  onConfirm: () => void;
  children: React.ReactElement;
}> = ({ onConfirm, children }) => {
  return React.cloneElement(children, {
    onClick: (e: any) => {
      Modal.confirm({
        title: '确认清空交班清单?',
        content: '所有未保存的事项将被清除',
        okText: '确认清空',
        okType: 'danger',
        cancelText: '取消',
        onOk: onConfirm
      });
    }
  });
};

export default ShiftRecordPage;
